Repository thoth-station/stub-api, pull requests merged in 2020-02, with the labels that each got.

#54 Automatic update of dependency thoth-common from 0.9.26 to 0.10.2
  Pipfile.lock
Labels: bot, size/L

#60 Coala patch
  .coafile
  .thoth.yaml
  openshift/buildConfig-template.yaml
  run_codegen.py
  thoth/stub/api/__init__.py
  thoth/stub/api/info.py
  thoth/stub/client/grpc_client.py
  thoth/stub/grpc_server.py
Labels: approved, size/S

#57 Automatic update of dependency thoth-common from 0.10.2 to 0.10.5
  Pipfile.lock
Labels: bot, size/S

#58 Automatic update of dependency prometheus-flask-exporter from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/S

#52 Automatic update of dependency connexion from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot, size/S

#61 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#62 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#63 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/M

#64 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/XS

#65 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
