Repository thoth-station/stub-api, pull requests merged in 2020-01, with the labels that each got.

#38 Happy new year!
  run_codegen.py
  thoth/stub/__init__.py
  thoth/stub/api/info.py
  thoth/stub/client/grpc_client.py
  thoth/stub/configuration.py
  thoth/stub/grpc_server.py
  thoth/stub/openapi_server.py
Labels: size/S

#39 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/L

#41 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#40 Automatic update of dependency connexion from 2.4.0 to 2.5.1
  Pipfile.lock
Labels: bot, size/S

#43 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/S

#44 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#45 Automatic update of dependency jaeger-client from 4.2.0 to 4.3.0
  Pipfile.lock
Labels: bot, size/S
